# This file was generated by GoReleaser. DO NOT EDIT.
cask "docfresh" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "b1c195dcdf89834170314531a56c2a69be2c94b18c94d10bbaeea876994fe96f"
      url "https://github.com/suzuki-shunsuke/docfresh/releases/download/v#{version}/docfresh_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0a3eb3ef1bf924aae22bb24d988fcd8490db333eb9347e73bda33ce2df5845f2"
      url "https://github.com/suzuki-shunsuke/docfresh/releases/download/v#{version}/docfresh_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "35fbb56801a0987034695964482d2c422f4d81d2ca1749a17180f12478ad45ff"
      url "https://github.com/suzuki-shunsuke/docfresh/releases/download/v#{version}/docfresh_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ad710c3b760c50f640ee912c85bdca15eb74aefae7a44448a836199c9a30f819"
      url "https://github.com/suzuki-shunsuke/docfresh/releases/download/v#{version}/docfresh_linux_arm64.tar.gz"
    end
  end

  name "docfresh"
  desc "Make document maintainable, reusable, and testable."
  homepage "https://github.com/suzuki-shunsuke/docfresh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "docfresh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/docfresh"]
    end
  end

  # No zap stanza required

end
