# This file was generated by GoReleaser. DO NOT EDIT.
cask "docfresh" do
  name "docfresh"
  desc "Make document maintainable, reusable, and testable."
  homepage "https://github.com/suzuki-shunsuke/docfresh"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "docfresh"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/docfresh/releases/download/v#{version}/docfresh_darwin_amd64.tar.gz"
      sha256 "e1b3613341f5d2cf218786e45695c6af8daa2eeddca97943cd8fa930b8e0600e"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/docfresh/releases/download/v#{version}/docfresh_darwin_arm64.tar.gz"
      sha256 "05d8fb194eb5c2517aa39627f52e5debdeed1871ab99465c032051bd84a34715"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/docfresh/releases/download/v#{version}/docfresh_linux_amd64.tar.gz"
      sha256 "eb8e8874856906b031dfe7071e2bd9b59f2bdc971c47557064d6592eaa3af085"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/docfresh/releases/download/v#{version}/docfresh_linux_arm64.tar.gz"
      sha256 "06cdc81c8ace18c7058882490cb04422e334c395faab3aaec777c0187ce1e588"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/docfresh"]
    end
  end

  # No zap stanza required
end
