# This file was generated by GoReleaser. DO NOT EDIT.
cask "docfresh" do
  name "docfresh"
  desc "Make document maintainable, reusable, and testable."
  homepage "https://github.com/suzuki-shunsuke/docfresh"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "docfresh"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/docfresh/releases/download/v#{version}/docfresh_darwin_amd64.tar.gz"
      sha256 "c293029758bbf67a0aadda2bb658272b0483669573a80ddef0b054db9ba85cc8"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/docfresh/releases/download/v#{version}/docfresh_darwin_arm64.tar.gz"
      sha256 "e71a918bfc90163193c383c1807c2acce9757aa6318b63fbdde95cd58e078812"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/docfresh/releases/download/v#{version}/docfresh_linux_amd64.tar.gz"
      sha256 "a9d336a451beee29011fd99937076132f70260f93653dd1cfba6cdce716cadb4"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/docfresh/releases/download/v#{version}/docfresh_linux_arm64.tar.gz"
      sha256 "dbd1df7038eb1cef2f826ff688718f6b9ab835ba64ed21107360fb8846afa5c6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/docfresh"]
    end
  end

  # No zap stanza required
end
